language: perl
perl:
  - '5.20'
after_success:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_8969d40ddede_key -iv $encrypted_8969d40ddede_iv -in travis/deploy_key.enc -out ../deploy.key -d
  - cp ../deploy.key ~/.ssh/
  - chmod 600 ~/.ssh/deploy.key
  - git remote set-url origin git@github.com:Songmu/TravisExperiment.git
  - script/tagify
